services:
 backend:
   image: bhaumikbcg/chat_backend:lts
   build:
     context: ./Backend # Path to the backend Dockerfile
   ports:
     - "8080:8080"


 backend2:
   image: bhaumikbcg/chat_backend2:lts
   build:
     context: ./Backend # Path to the backend Dockerfile
   ports:
     - "8084:8080"


 auth-backend:
   image: bhaumikbcg/chat_auth-backend:lts
   build:
     context: ./Auth_backend # Path to the backend Dockerfile
   ports:
     - "8081:8081" 


 frontend:
   image: bhaumikbcg/chat_frontend:lts
   build:
     context: ./Frontend/hhld_chat_frontend # Path to the frontend Dockerfile
   ports:
     - "3000:3000"
   depends_on:
     - backend # Wait for backend service to be ready before starting frontend


 frontend2:
   image: bhaumikbcg/chat_frontend2:lts
   build:
     context: ./Frontend2/hhld_chat_frontend # Path to the frontend Dockerfile
   ports:
     - "3001:3000"
   depends_on:
     - backend # Wait for backend service to be ready before starting frontend